pub const MAX_AUTOTUNING_BATCH_EXAMPLES: usize = 16;
pub const MAX_AUTOTUNING_SOURCE_DOCUMENTS: usize = 4;
pub const MAX_AUTOTUNING_RETRIEVAL_QUERIES: usize = 4;
pub const MAX_AUTOTUNING_GENERATION_RETRIEVAL_FANOUT: usize = 24;
pub const AUTOTUNING_OPERATION_DEADLINE_SECS: u64 = 1500;
pub const AUTOTUNING_OPERATION_PERSISTENCE_MARGIN_SECS: u64 = 60;
pub const AUTOTUNING_OPERATION_RUNTIME_DEADLINE_SECS: u64 =
    AUTOTUNING_OPERATION_DEADLINE_SECS - AUTOTUNING_OPERATION_PERSISTENCE_MARGIN_SECS;
pub const AUTOTUNING_RUNTIME_TIMEOUT_HEADER: &str = "x-nauron-autotuning-runtime-timeout-ms";
pub const MIN_AUTOTUNING_CLIENT_TIMEOUT_SECS: u64 = 1620;
